### PR TITLE
Update docker-compose.yml with latest cAdvisor and InfluxDB 0.9

### PR DESCRIPTION
**Pull request by marcellodesales**
This commit upgrades docker-compose with the latest cAdvisor, compatible with the 
latest version of InfluxDB. This was part of the https://github.com/google/cadvisor/pull/1040#issuecomment-176078952.

This solves the issue with #3.

@vegasbrianc Verify this in your environment! I'm using the cAdvisor and InfluxDB in `PROD` already :+1:

### CODE REVIEW

**Comment by vegasbrianc** [comment]
Thanks @marcellodesales for the PR. I will test this and merge this on Friday. I really appreciate it.

**Comment by marcellodesales** [comment]
@vegasbrianc No worries! Let me know how it goes!

**Comment by vegasbrianc** [comment]
Hi @marcellodesales I tried to test the PR. So far everything is running but the InfluxDB is not populating the database. I will look into it and let you know.

**Comment by vegasbrianc** [comment]
@marcellodesales The docker-compose is still reflecting 0.8.8 InlfuxDB version. Which version did you test with

**Comment by vegasbrianc** [comment]
Hi @marcellodesales Works great once I switched to your patch :+1: Thanks a ton for the PR and the work your did!

**Comment by vegasbrianc** [comment]
Wow, a lot of cool features. I think I will need to write up a follow-up article regarding the changes.

**Comment by marcellodesales** [comment]
@vegasbrianc Please count on me for the write-up!!! I Would love to! We can explore the new TICK platform from InfluxData... ;) It's been on my top priorities!

**Pull request merged**
